name: sudoku_app
description: A complete Sudoku game in Flutter.
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  shared_preferences: ^2.0.15
  sqflite: ^2.0.0+4
  path: ^1.8.0
  audioplayers: ^5.0.0
#  google_mobile_ads: ^2.0.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  
flutter:
  uses-material-design: true
  assets:
    - assets/sudoku_levels.json
    - assets/audio/bg.mp3
    - assets/audio/click.mp3
    - assets/audio/success.mp3
